services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    command: gunicorn dj_money.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - redis
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A dj_money worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
