version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY='django-insecure-1!05pj*pg&7xymg(f%m&fu5hzs!6-@#a5(etg^5@owgr0k9o6)'
      - DATABASE_URL=postgresql://dj_money:dj_money@db:5432/dj_money
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dj_money
      - POSTGRES_PASSWORD=dj_money
      - POSTGRES_DB=dj_money
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres_data: