services:
  web:
    volumes:
      - .:/app
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--requirepass", "dj_money"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
# Next docker-compose.dev.yml or docker-compose.prod.yml