# Generated by Django 4.1.7 on 2023-05-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.bankcard'),
        ),
    ]
