# Generated by Django 4.1.7 on 2023-05-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_transaction_currency_transaction_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_processing',
            field=models.DateField(default=None),
        ),
    ]
