# Generated by Django 4.1.7 on 2023-06-02 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_alter_bankexportfiles_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_to_account', to='money.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход'), ('transfer', 'Перевод')], max_length=10),
        ),
    ]
