# Generated by Django 4.1.7 on 2023-06-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0012_transaction_to_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_original_currency', to='money.currency'),
        ),
    ]
