# Generated by Django 4.1.7 on 2023-06-20 20:04

from django.db import migrations, models
import money.validators


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0013_transaction_original_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankexportfiles',
            name='sourse',
            field=models.CharField(choices=[('halyk', 'Halyk'), ('ziirat', 'Ziirat')], default='halyk', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankexportfiles',
            name='document',
            field=models.FileField(upload_to='files/', validators=[money.validators.validate_file_extension]),
        ),
    ]
