# Generated by Django 4.1.7 on 2023-07-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0015_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankexportfiles',
            name='sourse',
            field=models.CharField(choices=[('halyk', 'Halyk'), ('ziirat', 'Ziirat'), ('deniz', 'Deniz')], default='halyk', max_length=10),
        ),
    ]
