# Generated by Django 4.1.7 on 2025-06-11 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0017_alter_bankexportfiles_sourse_transactioncashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankexportfiles',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes or comments about the import process'),
        ),
        migrations.AddField(
            model_name='bankexportfiles',
            name='s3_file_key',
            field=models.CharField(blank=True, help_text='Files key in S3', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bankexportfiles',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('PROCESSING', 'В обработке'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='bankexportfiles',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
