# Generated by Django 4.1.7 on 2025-06-14 13:24

from django.db import migrations, models
import django.db.models.deletion
import money.validators


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0018_bankexportfiles_notes_bankexportfiles_s3_file_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bankexportfiles',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='statement_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='money.bankexportfiles'),
        ),
        migrations.AlterField(
            model_name='bankexportfiles',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[money.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='bankexportfiles',
            name='sourse',
            field=models.CharField(choices=[('halyk', 'Halyk'), ('ziirat', 'Ziirat'), ('deniz', 'Deniz'), ('kaspikz', 'Kaspi.kz'), ('bcc', 'BCC.kz')], default='bcc', help_text='Source bank type', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankexportfiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of file upload'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'transaction_type', 'date', 'date_processing', 'amount', 'currency', 'comment')},
        ),
    ]
