# Generated by Django 4.1.7 on 2025-06-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0019_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'transaction_type', 'date', 'date_processing', 'amount', 'currency', 'original_amount', 'original_currency', 'comment')},
        ),
    ]
