# Generated by Django 4.1.7 on 2025-06-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0020_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'transaction_type', 'date', 'date_processing', 'original_amount', 'original_currency', 'comment')},
        ),
    ]
