# Generated by Django 4.1.7 on 2025-06-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0021_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='for_categorized',
            field=models.BooleanField(default=True, help_text='Use this category for categorization of transactions'),
        ),
    ]
