# Generated by Django 5.2.3 on 2025-06-22 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0022_expensecategory_for_categorized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankexportfiles',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='bankexportfiles',
            unique_together={('user', 's3_file_key', 'sourse')},
        ),
    ]
