# Generated by Django 5.2.3 on 2025-06-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0023_alter_bankexportfiles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(db_index=True, help_text='Celery task ID', max_length=255, unique=True)),
                ('model_name', models.CharField(help_text='The name of the model used', max_length=100)),
                ('prompt', models.TextField(help_text='The full prompt sent to the model')),
                ('result', models.TextField(blank=True, help_text='The full result received from the model')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
