# Generated by Django 5.2.3 on 2025-06-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0024_gptlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_keyword', models.CharField(db_index=True, help_text="Keyword to match in the transaction's place/comment.", max_length=255)),
                ('match_type', models.CharField(choices=[('EXACT', 'Точное совпадение'), ('CONTAINS', 'Содержит')], default='CONTAINS', max_length=10)),
                ('category', models.ForeignKey(help_text='The category to assign if a match is found.', on_delete=django.db.models.deletion.CASCADE, to='money.expensecategory')),
                ('user', models.ForeignKey(help_text='The user this rule belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('user', 'place_keyword', 'category')},
            },
        ),
    ]
