# Generated by Django 5.2.3 on 2025-06-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0026_refactor_bank_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksource',
            name='parser',
            field=models.CharField(blank=True, help_text="Name parser's Class", max_length=255, null=True),
        ),
    ]
