# Generated by Django 5.2.3 on 2025-07-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0027_banksource_parser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_log', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gpt_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.gptlog')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.transaction')),
            ],
        ),
    ]
