# Generated by Django 5.2.3 on 2025-07-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0028_transactioncategorylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'transaction_type', 'date', 'date_processing', 'amount', 'currency', 'original_amount', 'original_currency', 'comment')},
        ),
    ]
